category_name = "Healthstone"
category_color = 0x93E5AB
category_description = { _ = "Just a healthstone." }


[healthstone]
enabled_by_default = false
name = "Healthstone"
description = { _ = "Just your typical healthstone." }
color = 0x93E5AB
items = [5512]
