category_name = "Healthstone"
category_color = 0x93E5AB
category_description = { _ = "Just a healthstone." }

mergeable = true
merged_by_default = true

[healthstone]
enabled_by_default = false
name = "Healthstone"
description = { _ = "Just your typical healthstone." }
color = 0x93E5AB
items = [5512]